// Auto-generated by `npm run bindings:export`. Do not edit manually.

// This file has been generated by Specta. DO NOT EDIT.

export type AccountSummary = { id: string; number: string; name: string; accountType: string; normalBalance: string; balanceMinor: number }

export type AccountantPackageEntry = { relativePath: string; sha256: string; bytes: number; entryType: string }

export type AccountantPackageExportCreateInput = { fiscalYear: number; idempotencyKey: string; exportDirectory: string | null }

export type AccountantPackageExportSummary = { packagePath: string; manifest: AccountantPackageManifest }

export type AccountantPackageImportValidateInput = { packagePath: string }

export type AccountantPackageManifest = { version: number; workspaceId: string; workspaceName: string; fiscalYear: number; createdAt: string; entries: AccountantPackageEntry[]; manifestSha256: string }

export type AccountantPackageValidateSummary = { valid: boolean; workspaceId: string; workspaceName: string; fiscalYear: number; entryCount: number; manualFallbackHint: string }

export type AppError = { code: string; message: string; details: FieldError[] | null }

export type BackupCreateInput = { idempotencyKey: string; destinationPath: string | null; backupFilePath: string | null; passphrase: string }

export type BackupManifest = { version: number; workspaceId: string; workspaceName: string; createdAt: string; entries: BackupManifestEntry[]; manifestSha256: string }

export type BackupManifestEntry = { relativePath: string; sha256: string; bytes: number; entryType: string }

export type BackupRestoreInput = { backupPath: string; confirmOverwrite: boolean; passphrase: string }

export type BackupRestoreSummary = { databasePath: string; workspaceId: string; workspaceName: string }

export type BackupSummary = { backupPath: string; manifest: BackupManifest }

export type BusinessProfile = { id: string; businessName: string; ownerName: string; residencyCountry: string; sniCode: string | null }

export type BusinessProfileSaveInput = { businessName: string; ownerName: string; residencyCountry: string | null; sniCode: string | null }

export type CashflowOverview = { bankBalanceMinor: number; receivablesBalanceMinor: number; vatReserveMinor: number; taxReserveMinor: number; spendableCashMinor: number; vatPeriodKey: string | null; thresholdWarning: string | null }

export type CommandResponse<T> = { data: T }

export type ComplianceCheckInput = { scenarioId: string }

export type ComplianceCheckResult = { scenarioId: string; passed: boolean; outcomes: JsonValue; ruleYear: number }

export type Counterparty = { id: string; kind: string; name: string; email: string | null; orgNumber: string | null }

export type CounterpartyCreateInput = { kind: string; name: string; email: string | null; orgNumber: string | null }

export type CsvImportCreateInput = { sourcePath: string; idempotencyKey: string }

export type CsvImportSummary = { id: string; stagedCount: number; firstStagedTransactionId: string }

export type Document = { id: string; objectPath: string; contentSha256: string; mimeType: string; originalFilename: string; retentionYears: number }

export type DocumentImportInput = { sourcePath: string; filename: string; mimeType: string; idempotencyKey: string }

export type DocumentGetInput = { documentId: string }

export type DocumentListInput = { unattachedOnly: boolean | null; limit: number | null; beforeId: string | null }

export type ExpensePostInput = { amountMinorExVat: number; vatRate: number; expenseAccountNumber: string; paymentAccountNumber: string; documentId: string | null; noDocumentReason: string | null; stagedTransactionId: string | null; idempotencyKey: string; date: string | null }

export type ExpensePostResult = { voucherId: string | null; debitExpenseMinor: number; debitInputVatMinor: number; creditPaymentMinor: number }

export type FieldError = { field: string | null; message: string; code: string }

export type FiscalPeriodSummary = { id: string; fiscalYearId: string; fiscalYear: number; periodKey: string; startsOn: string; endsOn: string; status: string }

export type IntegrationStatus = { available: boolean; provider: string; manualFallbackHint: string }

export type IntegrationStatusResponse = { openBanking: IntegrationStatus; bankid: IntegrationStatus }

export type InvoiceCreateDraftInput = { counterpartyId: string; dueDate: string | null; lines: InvoiceLineInput[] }

export type InvoiceCreditInput = { sourceInvoiceId: string; idempotencyKey: string; reason: string | null }

export type InvoiceIssueInput = { invoiceId: string; idempotencyKey: string; issueDate: string | null }

export type InvoiceLine = { id: string; lineOrder: number; description: string; quantity: number; unitPriceMinor: number; vatRateBp: number; accountNumber: string; lineExVatMinor: number; lineVatMinor: number }

export type InvoiceLineInput = { description: string; quantity: number; unitPriceMinor: number; vatRate: number; accountNumber: string | null }

export type InvoiceListInput = { status: string | null }

export type InvoicePdfStatusInput = { invoiceId: string }

export type InvoiceSummary = { id: string; counterpartyId: string; counterpartyName: string; status: string; invoiceKind: string; invoiceNumber: string | null; sourceInvoiceId: string | null; issueDate: string | null; dueDate: string | null; totalExVatMinor: number; totalVatMinor: number; totalIncVatMinor: number; pdfJobId: string | null; pdfDocumentId: string | null; voucherId: string | null; paymentVoucherId: string | null; lines: InvoiceLine[] }

export type InvoiceUpdateDraftInput = { invoiceId: string; dueDate: string | null; lines: InvoiceLineInput[] }

export type JournalLineRow = { accountNumber: string; accountName: string; debitMinor: number; creditMinor: number; vatCode: string | null }

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type NeFieldSummary = { fieldCode: string; amountMinor: number; sourceType: string; sourceRef: string | null }

export type RecentWorkspaceEntry = { id: string; name: string; databasePath: string; lastOpenedAt: string }

export type ReconciliationMatchCreateInput = { stagedTransactionId: string; matchKind: string; invoiceId: string | null; idempotencyKey: string }

export type ReconciliationMatchResult = { matchId: string; voucherId: string | null }

export type RuleVersionSummary = { id: string; taxYear: number; sourceUrl: string; status: string }

export type SieExportCreateInput = { fiscalYear: number; idempotencyKey: string; exportDirectory: string | null }

export type SieExportSummary = { exportPath: string; fiscalYear: number; voucherCount: number; accountCount: number }

export type StagedTransactionSummary = { id: string; csvImportId: string | null; transactionDate: string; description: string; amountMinor: number; status: string }

export type StagedTransactionsListInput = { status: string | null; limit: number | null; beforeId: string | null }

export type TaxProfile = { id: string; taxStatus: string; expectedBusinessProfitMinor: number; expectedSalaryIncomeMinor: number; activeRuleYear: number }

export type TaxProfileSaveInput = { taxStatus: string; expectedBusinessProfitMinor: number | null; expectedSalaryIncomeMinor: number | null; activeRuleYear: number | null }

export type VatProfile = { id: string; vatStatus: string; reportingPeriod: string; accountingMethod: string; voluntaryRegistrationDate: string | null }

export type VatProfileSaveInput = { vatStatus: string; reportingPeriod: string; accountingMethod: string; voluntaryRegistrationDate: string | null }

export type VatReturnApproveInput = { vatReturnId: string; idempotencyKey: string }

export type VatReturnBox = { boxCode: string; amountMinor: number; sourceQueryHash: string | null }

export type VatReturnDraftCreateInput = { periodKey: string; idempotencyKey: string }

export type VatReturnExportInput = { vatReturnId: string; exportDirectory: string | null }

export type VatReturnGetInput = { vatReturnId: string }

export type VatReturnSummary = { id: string; fiscalPeriodId: string; periodKey: string; status: string; ruleVersionId: string; boxes: VatReturnBox[]; box49AmountMinor: number; zeroReturn: boolean; exportPath: string | null }

export type VatThresholdStatus = { annualTurnoverMinor: number; thresholdMinor: number; warning: string; mustRegisterForVat: boolean; mustChargeVat: boolean }

export type VoucherCountInput = { status: string | null }

export type VoucherDetail = { id: string; status: string; sourceType: string; sourceId: string | null; fiscalYearId: string | null; accountingDate: string | null; postedAt: string | null; documentId: string | null; noDocumentReason: string | null; lines: JournalLineRow[] }

export type VoucherGetInput = { voucherId: string }

export type VoucherListInput = { status: string | null; sourceType: string | null; limit: number | null; beforeId: string | null }

export type VoucherSummary = { id: string; status: string; sourceType: string; sourceId: string | null; accountingDate: string | null; postedAt: string | null; debitTotalMinor: number; creditTotalMinor: number; lineCount: number; documentId: string | null }

export type WorkspaceCreateInput = { name: string }

export type WorkspaceOpenInput = { databasePath: string }

export type WorkspaceSettings = { id: string; locale: string; updaterEnabled: boolean; defaultExportDirectory: string | null; defaultBackupDirectory: string | null; dashboardTourCompleted: boolean; simpleMode: boolean }

export type WorkspaceSettingsSaveInput = { locale: string; updaterEnabled: boolean | null; defaultExportDirectory: string | null; defaultBackupDirectory: string | null; simpleMode: boolean | null }

export type WorkspaceSummary = { id: string; name: string; dataDir: string; databasePath: string }

export type YearEndPackageApproveInput = { packageId: string; idempotencyKey: string }

export type YearEndPackageCreateInput = { fiscalYear: number; idempotencyKey: string }

export type YearEndPackageExportInput = { packageId: string; idempotencyKey: string; exportDirectory: string | null }

export type YearEndPackageFindInput = { fiscalYear: number }

export type YearEndPackageGetInput = { packageId: string }

export type YearEndPackageSummary = { id: string; fiscalYearId: string; fiscalYear: number; status: string; ruleVersionId: string; k1Allowed: boolean; neDraftPresent: boolean; storedLocally: boolean; exportPath: string | null; fiscalYearLocked: boolean; neFields: NeFieldSummary[] }

export type YearEndReadiness = { items: YearEndReadinessItem[]; readyToApprove: boolean }

export type YearEndReadinessInput = { fiscalYear: number }

export type YearEndReadinessItem = { code: string; satisfied: boolean; detail: string | null }

