fn main() {
    let bindings = oppenbokforing_desktop_lib::bindings::export_types();
    let output = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/bindings.ts");
    let header = "// Auto-generated by `npm run bindings:export`. Do not edit manually.\n\n";
    std::fs::write(&output, format!("{header}{bindings}"))
        .expect("failed to write TypeScript bindings");
    println!("Wrote {}", output.display());
}
